version: '3.4'

services:
  registry-app:
    image: program
    stdin_open: true
    tty: true
    container_name: program.app
    build:
      context: .
      dockerfile: Dockerfile-clinic
    depends_on:
      - registry-db

  registry-db:
    image: mysql:latest
    container_name: clinic.db
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_DATABASE=clinicsregistry
    volumes:
      - ./clinicsDb:/var/lib/mysql
    ports:
      - 5001:3306